[package]
name = "ld54-limited-space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy-inspector-egui = "0.19.0"
bevy_rapier3d = "0.22.0"
log = "0.4.20"
rand = "0.8.5"
